export {default as Features} from './Features'
export {default as Trending} from './Trending'
export {default as Partners} from './Partners'
export {default as Promos} from './Promos'
export {default as Newsletter} from './Newsletter'
